import type { EvidenceIcon } from "@/lib/engine/types";

/**
 * Evidence sprites — 16×16 pixel art, one per evidence icon.
 * '.' is transparent; every other character is looked up in the sprite's
 * palette, falling back to the shared palette below.
 */

export interface Sprite {
  rows: string[];
  palette: Record<string, string>;
}

export const SHARED_PALETTE: Record<string, string> = {
  k: "#0b0d12", // outline
  w: "#ece6d6", // paper
  g: "#8a97a8", // steel
  r: "#c23a48", // seal red
  y: "#e8a849", // amber
  t: "#4fd8c4", // teal
};

export const SPRITES: Record<EvidenceIcon, Sprite> = {
  vial: {
    palette: { d: "#8a5a2c", e: "#b8834a", c: "#9fc4d4", a: "#4fd8c4", b: "#2a8a7c", h: "#c8fff4" },
    rows: [
      "................",
      "......kkkk......",
      "......keek......",
      "......kddk......",
      ".....kkkkkk.....",
      "......kcwk......",
      "......kcwk......",
      ".....kccwck.....",
      "....kcccccwk....",
      "...kcaaaaaack...",
      "...kahaaaaabk...",
      "..kahaaaaaaabk..",
      "..kaaaaaaaaabk..",
      "..kaaaaaaaabbk..",
      "...kbbbbbbbbk...",
      "....kkkkkkkk....",
    ],
  },
  letter: {
    palette: { f: "#b8ad94", s: "#d8d0bc" },
    rows: [
      "................",
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kfwwwwwwwwwwfk.",
      ".kwfwwwwwwwwfwk.",
      ".kwwfwwwwwwfwwk.",
      ".kwwwfwwwwfwwwk.",
      ".kwwwwfrrfwwwwk.",
      ".kwwwwrrrrwwwwk.",
      ".kwwwwwrrwwwwwk.",
      ".kswwwwwwwwwwsk.",
      ".ksssssssssssk..",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  photo: {
    palette: { c: "#24365a", d: "#1a2742", b: "#0d131e", e: "#d8d0bc" },
    rows: [
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kwwwwwwwwwwwwk.",
      ".kwccccccccywwk.",
      ".kwcccccccccwwk.",
      ".kwdddbddddcwwk.",
      ".kwddbbbdddbwwk.",
      ".kwdbbbbbdbbwwk.",
      ".kwbbybbbbbywwk.",
      ".kwbbbbbybbbwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".keeeeeeeeeeeek.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  print: {
    palette: { a: "#d8d2c4", b: "#9a9484" },
    rows: [
      "................",
      ".....aaaaaa.....",
      "...aa......aa...",
      "..a..aaaaaa..a..",
      ".a..a......a..a.",
      ".a.a..aaaa..a.a.",
      "a..a.a....a.a..a",
      "a.a..a.aa.a..a.a",
      "a.a.a..a..a.a..a",
      "a.a.a.a..a..a.a.",
      ".a.a..a.a..a..b.",
      ".a..a..a..a..b..",
      "..a..a...a..b...",
      "...b..aaa..b....",
      "....bb....b.....",
      "......bbbb......",
    ],
  },
  phone: {
    palette: { a: "#9a2e38", h: "#d0525e", b: "#5e1a22", c: "#c9c2b0" },
    rows: [
      "................",
      "................",
      "..kkkk....kkkk..",
      ".khaaak..khaaak.",
      ".kaaaakkkkaaaak.",
      ".kaaaaaaaaaaaak.",
      "..kkkaaaaaakkk..",
      "....kkkkkkkk....",
      "...khaaaaaaak...",
      "..khakwcwckaak..",
      "..kakwkkkkwkak..",
      ".khacwkggkwcaak.",
      ".kaakwkkkkwkaak.",
      ".kaaakcwcwkaaak.",
      ".kbbbbbbbbbbbbk.",
      "..kkkkkkkkkkkk..",
    ],
  },
  bank: {
    palette: { a: "#c9c2b0", h: "#ece6d6", b: "#8a8478", c: "#a8a090" },
    rows: [
      "................",
      ".......kk.......",
      ".....kkhhkk.....",
      "...kkhhaahhkk...",
      ".kkhaaaaaaaaakk.",
      ".kkkkkkkkkkkkkk.",
      "..khk.khk.khk...",
      "..kak.kak.kak...",
      "..kak.kak.kak...",
      "..kak.kak.kak...",
      "..kak.kak.kak...",
      "..kbk.kbk.kbk...",
      ".kkkkkkkkkkkkkk.",
      "kaaaaaaaaaaaaaak",
      "kbbbbbbbbbbbbbbk",
      "kkkkkkkkkkkkkkkk",
    ],
  },
  key: {
    palette: { a: "#c9a24a", h: "#f2d688", b: "#8a6a2a" },
    rows: [
      "................",
      "................",
      "................",
      "..kkkk..........",
      ".khhaak.........",
      "kha..aak........",
      "ka....akkkkkkkk.",
      "ka....ahhhhhhhak",
      "kaa..aabbbbbbbbk",
      ".kaaabkkkkkbkbkk",
      "..kkkk....kbkbk.",
      "..........kbkbk.",
      "...........kkkk.",
      "................",
      "................",
      "................",
    ],
  },
  knife: {
    palette: { s: "#9aa4b0", h: "#eef3f8", a: "#c9a24a", d: "#6a4428", e: "#8a5a34" },
    rows: [
      "................",
      ".............kk.",
      "............khk.",
      "...........khsk.",
      "..........khsk..",
      ".........khsk...",
      "........khsk....",
      ".......khsk.....",
      "......khsk......",
      "...kk.kssk......",
      "...kaakkk.......",
      "....kaak........",
      "...kdekak.......",
      "..kdek.kk.......",
      ".kdek...........",
      ".kkk............",
    ],
  },
  glass: {
    palette: { c: "#cfe4ee", s: "#6e8c9c", a: "#c8782a", b: "#8a4a18", h: "#f6e8c8", e: "#f0b85a" },
    rows: [
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      "..kc........sk..",
      "..kc........sk..",
      "..kc........sk..",
      "..kc........sk..",
      "..kceeeeeeeesk..",
      "..kcaahhaaaask..",
      "..kcaahhaaaask..",
      "..kcaaaaaaaask..",
      "..kcbaaaaaabsk..",
      "..kcbbbbbbbbsk..",
      "..kccccccccccsk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  watch: {
    palette: { a: "#c9a24a", h: "#f2d688", b: "#8a6a2a", f: "#b8b0a0" },
    rows: [
      "......kkkk......",
      "......k..k......",
      "......kkkk......",
      ".......kk.......",
      ".....kkhhkk.....",
      "...kkhaaaaakk...",
      "..khawwwwwwaak..",
      "..kawwwwkwwwab..",
      ".khawwwwkwwwwak.",
      ".kawwwwwkwwwwak.",
      ".kawwwwwkkkwwab.",
      ".kawfwwwwwwwfab.",
      "..kawwwwwwwwab..",
      "..kbawwfwwwabk..",
      "...kkbbaaabbkk..",
      ".....kkkkkk.....",
    ],
  },
  tape: {
    palette: { a: "#565c6a", h: "#7c8494", b: "#363a44", c: "#c9c2b0", e: "#e05c6e" },
    rows: [
      "................",
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".khhhhhhhhhhhhk.",
      ".kawwwwwwwwwwak.",
      ".kaweeewwwwwwak.",
      ".kaaaaaaaaaaaak.",
      ".kakccckkccckak.",
      ".kakckckkckckak.",
      ".kakccckkccckak.",
      ".kaaaaaaaaaaaak.",
      ".kbbbkkkkkkbbbk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  ledger: {
    palette: { a: "#2e6a50", h: "#4e9a76", b: "#1c4434", e: "#d8d0bc" },
    rows: [
      "................",
      "...kkkkkkkkkk...",
      "..khaaaaaaaaak..",
      "..khaaaaaaaaak..",
      "..khayyyyyyaak..",
      "..khaykkkkyaak..",
      "..khayyyyyyaak..",
      "..khaaaaaaaaak..",
      "..khaaaaaaaaak..",
      "..khaaaaaaaaak..",
      "..khaaaaaaaaak..",
      "..khaaaaaaaaak..",
      "..kbbbbbbbbbbk..",
      "..kweeeeeeeewk..",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  ticket: {
    palette: { e: "#d8d0bc", f: "#b8ad94" },
    rows: [
      "................",
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      "kwwwwwwwwwfwwwwk",
      "kwkkkkkkwwewrrwk",
      "kwwwwwwwwwfwrrwk",
      ".kwkkkkwwwewwwk.",
      ".kwwwwwwwwfwwwk.",
      "kwkkkkkkkwewwwwk",
      "kwwwwwwwwwfwkkwk",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  badge: {
    palette: { a: "#d8b04a", h: "#f6e09a", b: "#8a6a1a", c: "#b08a2a" },
    rows: [
      "................",
      "..kkkkkkkkkkkk..",
      ".khhaaaaaaaaaak.",
      ".khaaaaaaaaaack.",
      ".khaaaabaaaaack.",
      ".khaaabbbaaaack.",
      ".khabbbbbbbaack.",
      ".khaabbbbbaaack.",
      ".khaabbabbaaack.",
      "..khaaaaaaaack..",
      "..khaaaaaaaack..",
      "...khaaaaaack...",
      "....khaaaack....",
      ".....khaack.....",
      "......kcck......",
      ".......kk.......",
    ],
  },
  cloth: {
    palette: { a: "#9a9aa4", h: "#c4c4cc", b: "#62626c", c: "#7a7a84" },
    rows: [
      "................",
      "................",
      "..kkkkkkkkk.....",
      ".khhhhhhhhhkk...",
      ".khacacacachak..",
      ".kcacacacacahk..",
      ".khacacacacacak.",
      ".kcacacacacacak.",
      ".khacacacacacak.",
      ".kcacacacacacabk",
      "..kacacacacacabk",
      "..kbcbcbcbcbcbk.",
      "...kbbkbbkbbkk..",
      "....k.k..k..k...",
      "....k....k......",
      "................",
    ],
  },
  pill: {
    palette: { a: "#c8781e", h: "#f0a848", b: "#8a4a10", c: "#d8d2c4" },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kwwwwwwwwk...",
      "...kcwcwcwcwk...",
      "....kkkkkkkk....",
      "...khaaaaaaaak..",
      "..khawwwwwwwak..",
      "..khawrrrwwwak..",
      "..khawwwwwwwak..",
      "..khawkkkkwwak..",
      "..khawwwwwwwak..",
      "..khaaaaaaaaak..",
      "..khaaaaaaaabk..",
      "..kbbbbbbbbbbk..",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  rope: {
    palette: { a: "#b8955a", h: "#e6cc92", b: "#7a5a30" },
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkhaahaakk...",
      "..khab....bahk..",
      ".kha..kkkk..ahk.",
      ".ka..khaahk..ak.",
      "kha.kab..bak.ahk",
      "ka.ka......ak.ak",
      "ka.ka......ak.ak",
      "kha.kab..bak.ahk",
      ".ka..khaahk..ak.",
      ".kha..kkkk..abk.",
      "..khab....babk..",
      "...kkbaabaakk...",
      ".....kkkkkkbak..",
      "...........kkbk.",
    ],
  },
  camera: {
    palette: { a: "#5a4c40", h: "#7e6a58", b: "#3a3028", c: "#b8c0c8", e: "#e8eef4", l: "#2a3a52" },
    rows: [
      "................",
      "................",
      "..kkkk.....kkk..",
      ".kcccck...kccck.",
      ".kkkkkkkkkkkkkk.",
      ".khhhhhhhhhhhhk.",
      ".kaaaakkkkkaaak.",
      ".kaaakllllkaaak.",
      ".kaaklelllkkaak.",
      ".kaakllllllkaak.",
      ".kaaklllllkkaak.",
      ".kaaakllllkaaak.",
      ".kaaaakkkkkaaak.",
      ".kbbbbbbbbbbbbk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  folder: {
    palette: { a: "#d4b070", h: "#f0d49a", b: "#a0803e", e: "#c23a48" },
    rows: [
      "................",
      "................",
      ".kkkkkk.........",
      "khaaaaak........",
      "kaaaaaaakkkkkkk.",
      "khhhhhhhhhhhhhak",
      "khaaaaaaaaaaaaak",
      "khaaaaaaaaaaaaak",
      "khaaaaeeeeaaaaak",
      "khaaaaaaaaaaaaak",
      "khaaaaaaaaaaaaak",
      "khaaaaaaaaaaaaak",
      "kbbbbbbbbbbbbbbk",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
    ],
  },
  ring: {
    palette: { a: "#d8b04a", h: "#f6e09a", b: "#8a6a1a", c: "#2aa898", e: "#c8fff4" },
    rows: [
      "................",
      "......kkkk......",
      ".....kcetck.....",
      ".....kcttck.....",
      "......kcck......",
      ".....kkaakk.....",
      "...kkhb..baakk..",
      "..khb......bak..",
      ".khb........bak.",
      ".kh..........ak.",
      ".kh..........ak.",
      ".khb........bak.",
      "..kab......bak..",
      "...kkaaaaaaakk..",
      ".....kkkkkkk....",
      "................",
    ],
  },
};
